language: node_js
node_js:
  - 11.10.0
services:
  - docker
  - postgresql
install:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - mkdir ${HOME}/.kube
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - npm i
  - npm i -g k8ss
  - echo -e "machine github.com\n  login $GH_TOKEN" > ~/.netrc
  - git clone https://github.com/Jeff-Tian/k8s-config.git ${HOME}/k8s-config
cache:
  directories:
    - node_modules
env:
  ci: true
before_install:
  - psql -U postgres < src/db/init.sql
before_script:
  - echo "before script..."
script:
  - npm test
  - npm run test:e2e
  - sh .travis/ci.sh
deploy:
  - provider: script
    skip_cleanup: true
    script: npm run okteto
    on:
      branch: main
