apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: uni-orders
    tier: backend
    deployedBy: deploy-node-app
  name: uni-orders
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: uni-orders
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: uni-orders
        tier: backend
        deployedBy: deploy-node-app
    spec:
      containers:
        - image: jefftian/uni-orders
          imagePullPolicy: Always
          name: uni-orders
          env:
            - name: GET_HOSTS_FROM
              value: dns
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
            - containerPort: 5005
              name: grpc
              protocol: TCP
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5005"]
            initialDelaySeconds: 5
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5005"]
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 64Mi
          envFrom: []
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
